bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
setw -g mouse on

# Change prefix from 
set-option -g prefix C-s

bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

bind-key - split-window -h
bind-key = split-window -v

bind -n S-Left previous-window
bind -n S-Right previous-window

set -g status-bg colour8
set -g status-fg colour11

