bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
#setw -g mouse on

# Change prefix from 'Ctrl+b' to 'Ctrl+t'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

